- README.md
- src/index.ts
- src/middleware/body.parser.ts
- src/server/apollo.server.ts
- src/server/server.ts
- expose Server#app, IApolloServerArgs for use by `supertest`
- use 'error' listeners during Server#start and #stop
- implement 'Content-Type: application/graphql' support
> server-core - support for `event-service` Test Suite

- package.json
- src/authentication/token.check.ts
- src/middleware/error.logging.spec.ts
- src/middleware/error.logging.ts
- src/server/apollo.context.ts
- src/server/apollo.server.ts
- src/server/server.ts
- yarn.lock
- new ErrorRequestHandler for express / REST calls
- Apollo `formatError` handler for "enrichedError" (vs. Error instance)
- "logging" = send a JSON payload to `console.error`
- Promise#reject should be given an Error instance, not a String
- "Property 'token' does not exist on type 'Request'."
> server-core - support for both REST and GraphQL Error logging

- package.json
- src/authentication/token.check.spec.ts
- src/authentication/token.check.ts
- src/authentication/verify.token.spec.ts
- src/authentication/verify.token.ts
- src/server/apollo.context.ts
- yarn.lock
- extract ID Token from the 'Authorization' header, removing "Bearer " prefix
- error logging upon `identity_service` request failure
i think we can get away with just a PATCH on this change
> server-core - auth never succeeding, everyone seems to be a Guest

- src/middleware/error.logging.ts
- src/templates/entity.template.ts
we aren't always relying upon TypeORM to auto-generate our UUIDs.  when we generate reproducible IDs during the Firebase import steps, we want to ensure they're unique from a database constraint perspective
`event_service` will execute the necessary migrations
i am making this a MINOR version -- because there will be implications to taking on the unique key
the developer will need to revert and re-generate the Entity.id indexes -- there will be a pratical example of this in the `event_service` repo
> server-core - `id` column / UUIDs should be unique

- src/graphql/core.types.ts
- test/apollo/core.types.date.ts
- Date { timezone } fallback to 'UTC' when timezone is blank
- Date { milliseconds } without 32-bit Int constraints
- Date { unixTimestamp } can be an Int
> server-core - GraphQL Date typedef fixes

- src/graphql/interservice.communication.spec.ts
- src/graphql/interservice.communication.ts
- builder is a Function which has captured { serviceUrl, query }
- builder returns a "caller" which has captured { token, variables }
- caller provides #fetch and #execute proxies to a ServiceCaller
this is an API enhancement of `ServiceCaller` which was the last MINOR.  a PATCH would be sufficient. if we wanted to be strict, we could call it a MINOR
> implement a currying ServiceCall "builder"

- jest.config.js
- package.json
- src/authentication/token.check.spec.ts
- src/authentication/token.check.ts
- src/authentication/verify.token.ts
- src/graphql/interservice.communication.spec.ts
- src/graphql/interservice.communication.ts
- src/index.ts
- src/middleware/error.logging.spec.ts
- src/middleware/error.logging.ts
- src/server/apollo.context.spec.ts
- src/server/apollo.context.ts
- src/server/apollo.server.ts
- src/server/server.init.ts
- src/server/server.ts
- yarn.lock
- formal @withjoy/telemetry integration
- `logContextRequest` for contiguous logging support
- Context-aware Plugin strategy for Apollo Error logging
- Context self-derives its #telemetry context
- custom header support for ServiceCaller & peers
- Context#me accepts ServiceCaller overrides
- added Context#req
- a Context can act as its own constructor args
- constants for 'no-user', 'no-token' also used by Apps
- upped coverage thresholds
> ENG-381 contiguous logging support for GraphQL Services

- src/authentication/verify.token.spec.ts
- src/authentication/verify.token.ts
- src/server/apollo.context.spec.ts
- src/server/apollo.context.ts
- Telemetry introspection into live Context state
- `decodeUnverifiedToken` - @Kaiwalya asked for an unpacked payload
- white-list only the JWT properties tha we log
> ENG-381 Telemetry context provides wider scope of details

- src/graphql/core.types.ts
- test/apollo/core.types.date.ts
- applied to DateFormat, TimeFormat, TimezoneFormat
- verified schema:check from `stitch_service` + ALL local services
> ENG-746 camelCase (vs. PascalCase) for "core" typedef Enum values

- src/index.ts
- src/middleware/defauits.spec.ts
- src/middleware/defaults.ts
- src/middleware/error.logging.spec.ts
- src/middleware/error.logging.ts
- src/server/server.ts
- getDefaultMiddleware => { preludes, bodyParsers, apollo }
- provide as Arrays and as a Map-by-Express-name for easy lookup
> ENG-559 middleware support for avoiding HTTP 413 errors

- package.json
- src/graphql/interservice.communication.ts
- src/middleware/error.logging.spec.ts
- src/middleware/error.logging.ts
- src/server/apollo.context.spec.ts
- src/server/apollo.context.ts
- too many CSV columns because of JSON parsing by Rapid7 / Datadog
> ENG-1813 exported logs are unusable

- src/middleware/defaults.ts
- src/middleware/session.ts
- src/server/apollo.config.ts
- src/server/server.ts
- *we* are responsible for CORS middleware, not Apollo
- support legacy Apollo Config, rather than upgrade
- implemented & disabled strategy for strict 'withjoy.com'
- went with a generous Developer-centric strategy
- do not enforce TLS on Cookie (also Developer-centric)
- OK with 'Cookie:  SameSite=Lax', per end-to-end testing
- Cookies are issued & picked up via. GraphQL `withCredentials`!
> ENG-2238 address CORS security RE: Cookie + Apollo GraphQL

- npm-shrinkwrap.json
- package.json
- src/index.ts
- src/node6.ts
- use `require("@withjoy/server-core/dist/node6")`
- added npm-shrinkwrap.json
when `typescript` went from 3.8 => 3.9, we started to have issues in `app-server-api`:
```
exports.EntityManager = EntityManager_1.EntityManager;
TypeError: Cannot set property EntityManager of #<Object> which has only a getter
at Object.<anonymous> (/jRunBad/node_modules/typeorm/index.js:117:23)
```
it seems that `Reflect.getOwnPropertyDescriptor(exports, 'EntityManager')` produces different results:
- TypeScript 3.8 => `{"writable":true,"enumerable":true,"configurable":true}`
- TypeScript 3.9 => `{"enumerable":true,"configurable":false}`
the best approach is to create a Node-6-specific `index.js` and only expose those things that `app-server-api` and the other monorepo modules really need (because they sure …
> adding formal support for Node 6

- npm-shrinkwrap.json
- package.json
- src/middleware/defaults.spec.ts
- src/middleware/defaults.ts
- src/server/apollo.context.spec.ts
- src/server/apollo.context.ts
- src/templates/model.template.ts
- yarn.lock
- `sessionId` is important for log correlation
- `forwarded` properly derives a remote IP address
- `path` vs. `url`, and consider GraphQL middleware rewrites
- `host` = HTTP requested host (vs. physical `hostname`)
> ENG-2499 reconciled logging between `morgan` and `logContextRequest`

- src/utils/virtualEvent/_helpers.ts
- src/utils/virtualEvent/index.spec.ts
- src/utils/virtualEvent/index.ts
- src/utils/virtualEvent/schema.ts
- src/utils/virtualEvent/types.ts
- unless it's not present, in which case parse => `null`
- added VirtualEventProvider.unknown
- more optional properties, only available upon a valid parse
> VEN-312 always echo the `{ linkText }` when parsing a Virtual Event link

- .circleci/config.yml
- README.md
- a comment in a multi-line CircleCI `command` nukes its following shell lines
- prior `NPM_TOKEN` changes never worked; had to fix a bunch of things
- the `NPM_TOKEN` must have Publish rights
- updated README
> TP-131 CircleCI performs `yarn publish`

- src/graphql/core.types.spec.ts
- src/graphql/core.types.ts
- src/server/apollo.context.ts
- test/apollo/core.types.color.ts
- test/apollo/core.types.date.ts
- `{ timestamp }` is still ISO-8601, and always provides "[+-]HH:MM"
- formal TypeScript-ing of Resolver methods
- expanded Unit Testing, better scenario coverage
- simplified GraphQL end-to-end Date testing
And while I was at it,
- implemented `{ utcOffset }` but can't release it; ENG-746 deployment risks
- formal handling of parse Errors for Color, Date + timezone
> VEN-476 provide parseable timezone offset from CoreTypeDef `Date`

- src/utils/virtualEvent/_helpers.ts
- src/utils/virtualEvent/aggregator.spec.ts
- src/utils/virtualEvent/aggregator.ts
- src/utils/virtualEvent/eventlive.spec.ts
- src/utils/virtualEvent/eventlive.ts
- src/utils/virtualEvent/googleMeet.spec.ts
- src/utils/virtualEvent/index.ts
- src/utils/virtualEvent/schema.ts
- src/utils/virtualEvent/zoom.spec.ts
- src/utils/virtualEvent/zoom.ts
- test/apollo/virtualEvent.ts
- Zoom Web Client path is '/wc/join/:streamId'
- Eventlive parser support for 'eventlive.pro/event/:streamId'
- Eventlive Stream ID is now assumed to be Account-agnostic
- stricter parsing of Zoom URLs; known patterns only (App + Web Client)
And while I was at it,
- split out aggregator logic from 'index'; now index' is just `export`s
- provided standard GraphQL Resolvers (to match TypeDefs)
- GraphQL end-to-end testing
> VEN-476 Virtual Event parsing fixes

- src/utils/virtualEvent/aggregator.spec.ts
- src/utils/virtualEvent/aggregator.ts
- src/utils/virtualEvent/schema.ts
- src/utils/virtualEvent/types.ts
- test/apollo/virtualEvent.ts
This reverts commit 1677447d9bcebb0c8f7c71f7fd45166624bfc286.
the iOS Team has not submitted a version of the App that does a bad query to Apple for review.  the reason that we saw a failure when doing `ENVIRONMENT=production yarn schema:diff` is that they'd used Production for testing pre-release builds
> Revert "VEN-476 iOS did not migrate to `{ isPasswordDetected }`; we must re-introduce `{ passwordDetected }`"

- jest.config.js
- package.json
- src/graphql/core.types.ts
- src/graphql/federated.types.spec.ts
- src/graphql/federated.types.ts
- src/index.ts
- src/templates/controller.template.spec.ts
- src/templates/controller.template.ts
- src/templates/fake.model.ts
- src/templates/view.template.spec.ts
- src/templates/view.template.ts
- src/utils/edge.wrapper.ts
- test/apollo/core.types.color.ts
- test/apollo/core.types.jsonObject.ts
- yarn.lock
- ModelViewTemplate resolves CoreTypeDate for `{ createdAt, updatedAt }`
- ControllerTemplate gets `loadersMulti` + supporting wrappers & utilities
- utilities to output Federated references to common `@external` Service Type
- JSONObject as a core type, per `graphql-type-json`
- couldn't stop myself from updating the Pantone example to 130-U #2020hindsight
- upped the Test Coverage thresholds a wee bit
> CORE-823 migrate re-usable features from `event_service`

- src/middleware/defaults.spec.ts
- src/middleware/defaults.ts
- src/utils/miscellaneous.spec.ts
- src/utils/miscellaneous.ts
- test/helpers/apollo.ts
which is important to log tracing / correlation
- Session ID handling should be default middleware, vs. just Apollo
also
- `executeOperationsInParallel` passes standard Iterator arguments
- eliminated silly Apollo warning in Test Suite setup
> CHORE calls to logContextRequest are not getting the Session ID

- src/index.ts
- src/middleware/defaults.spec.ts
- src/middleware/defaults.ts
- src/middleware/error.logging.ts
- src/middleware/session.spec.ts
- src/middleware/session.ts
- src/middleware/types.ts
- src/server/server.init.ts
- src/server/server.ts
- this pattern works: `interface RequestWithSessionId extends Request`
- `type RequestHandlerVariant`, so that middleware supports ErrorRequestHandler
- `shutdownCurrentApp`, formalizing the SIGTERM approach
> CORE-1311 support for additional `express`-related features

- package.json
- src/index.ts
- src/middleware/defaults.spec.ts
- src/middleware/defaults.ts
- src/server/apollo.context.spec.ts
- src/server/apollo.context.ts
- src/server/apollo.errorPipeline.ts
- yarn.lock
- boilerplate for the flip-side of `injectContextIntoRequestMiddleware`
- optional Generics on both of those methods
- upgrade @withjoy/telemetry
- which revealed a TypeScript failure, as fixed by `{ msg: 'morgan' }`
> CORE-1400 implement `deriveContextFromRequest`

- package.json
- yarn.lock
to eliminate: 'warning Resolution field "typeorm@0.2.31" is incompatible with requested version "typeorm@0.2.13"'
> CHORE make `typeorm` version less strict

- src/index.ts
- src/utils/healthCheck/index.ts
- src/utils/healthCheck/postgres.spec.ts
- src/utils/healthCheck/postgres.ts
- src/utils/healthCheck/requestHandler.spec.ts
- src/utils/healthCheck/requestHandler.ts
- src/utils/healthCheck/typeormMigrations.spec.ts
- src/utils/healthCheck/typeormMigrations.ts
- src/utils/healthCheck/types.ts
- src/utils/healthCheck/utils.spec.ts
- src/utils/healthCheck/utils.ts
- src/utils/pg/index.spec.ts
- src/utils/pg/index.ts
- src/utils/typeorm/batch.pg.spec.ts
- src/utils/typeorm/batch.pg.ts
- src/utils/typeorm/batch.support.spec.ts
- src/utils/typeorm/batch.support.ts
- src/utils/typeorm/helpers.spec.ts
- src/utils/typeorm/index.ts
- src/utils/typeorm/migration.spec.ts
- src/utils/typeorm/migration.ts
- check for Postgres health
- check for un-applied TypeORM Migrations
- called out path-referenced toolkits (vs. part of formal exports)
- end-to-end database Test Cases live in '@withjoy/server-core-test'
- HealthCheckState as a convenient 'latch'
- simple "predicate" check wrapper for any `async` boolean Function
- 'prior me' couldn't spell "@withjoy/server-core-test" properly
> CORE-1608 shift Health Checks into '@withjoy/server-core'

- package.json
- src/graphql/core.types.ts
- tsconfig.json
Reason for change: 
In order for `graphql-code-generator` to identify graphlq types it needs an identifier wrapping the string. `gql` typically works but when the files are compiled with `tsc` the wrapper changes to `apollo_server_1.gql`. Moving the graphql types to a string with a `/* GraphQL */` comment accomplishes the same thing and wrapping this string in `gql` keeps everything the same as far as the exported object.
> graphql code generator friendly core types

- jest.config.js
- src/graphql/core.types.ts
- test/apollo/core.types.jsonObject.ts
- test/apollo/core.types.void.ts
- found out why our JSONObject Test Suite was mistakenly passing
> CHORE introduce Void GraphQL Scalar type

- src/index.ts
- src/server/apollo.context.ts
- src/utils/execution/batch.spec.ts
- src/utils/execution/batch.ts
- src/utils/execution/parallel.spec.ts
- src/utils/execution/parallel.ts
- src/utils/miscellaneous.spec.ts
- src/utils/miscellaneous.ts
- src/utils/typeorm/migration.ts
- `executeOperationsInBatches` lives in 'src/utils/execution'
- and `executeOperationsInParallel` lives there now, too
- exporting Parallel-related types (vs. interfaces)
- fixes from PR feedback on https://github.com/joylifeinc/product_service/pull/222
> REG-2252 adopt BatchPipelineExecutor

- src/utils/dotenv.spec.ts
- src/utils/dotenv.ts
having talked things over with @knkher , we can see how an accidental edit to the 'test/.env' file could lead to
uh
*... issues*.  such as, *i don't know*, deleting the contents of a database?  so we'll adopt a reasonable convention
> CHORE '_test' database naming convention to avoid nuking real-world data

- src/utils/url.spec.ts
- src/utils/url.ts
the way it was built, it would *always* convert the URL to 'https:'.  i'm shocked that this didn't bite us before
preserving the protocol during the sanitization process turns out to require some RegExp trickery, mostly because Node 10
i made the behavior conform to the prior spec per the Test Suite, then pushed it a bit farther to see what would happen
> CORE fixing issues with sanitizeUrlString and its sibling

- src/utils/healthCheck/postgres.ts
- src/utils/healthCheck/requestHandler.spec.ts
- src/utils/healthCheck/requestHandler.ts
- src/utils/healthCheck/typeormMigrations.ts
- src/utils/healthCheck/types.ts
- src/utils/healthCheck/utils.ts
- it does not contribute to the aggregate status, nor the duration, of the health check.
- its result is not included in the aggregate JSON payload of all checks.
- if the check fails, that gets logged independently.
also,
- re-align HEALTH_CHECKER_TIMEOUT_MS with current k8s configurations
- report { durationMs } in all the useful places
- ~holy shit!~  VSCode shows you Markdown if you use JSDoc style comments!
> SHOP-112 implement out-of-band HealthCheckers
